'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const source=fs.readFileSync('frontend/app.js','utf8');
assert.match(source,/STATE_KEY='ferrocat-state-v1\.1-functional'/);
assert.match(source,/schemaVersion:2/);
assert.match(source,/function sanitizeLine\(/);
assert.match(source,/sessionStorage\.removeItem\(STATE_KEY\)/);
assert.match(source,/String\(x\.name\|\|/);
assert.match(source,/\.slice\(0,80\)/);
assert.match(source,/COLORS\.includes\(x\.color\)/);
assert.match(source,/Number\.isFinite/);
assert.doesNotMatch(source,/\beval\s*\(/);
assert.doesNotMatch(source,/new Function\s*\(/);
console.log('proves de seguretat de l’estat del frontend: OK');
